name: Go

on: [push, pull_request]

jobs:
  build:
    name: Build
    runs-on: ${{ matrix.os }}
    
    strategy:
        matrix:
            os: [windows-latest, macOS-latest, ubuntu-latest]
            go_version: ['1.14']
            
    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ${{matrix.go_version}}
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Build
      run: go build -v .

    - name: Test
      run: go test -v .
      
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2
      with:
        name: ${{ matrix.os }}
        path: OpenTeach*
